name: Flutter Web
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Build Web
    env:
      my_secret: $
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: subosito/flutter-action@v1
        with:
          channel: 'dev'
      - run: flutter config --enable-web
      - run: flutter pub get
      - run: flutter build web --release
        working-directory: ./
      - run: |
          mv .gitattributes build/web
          cd build/web
          git init
          git config --global user.email phk09242@gmail.com
          git config --global user.name Park Dong UK
          git status
          git remote add origin https://github.com/ykh09242/portfolio_web.git 
          git checkout -b web_release
          git add --all
          git commit -m "update"
          git push origin web_release -f